########################################################
###Redis (RedisConfiguration)###########################
########################################################
#spring:
#  redis:
#    host: 127.0.0.1
#    pool: 6379
#    database: 1
#    password: 123456
#    timeout: 50000ms
#    jedis:
#      pool:
#      max-wait: -1ms
#      min-idle: 0
#      max-idle: 8
#      max-active: 8





